//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManager.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagVrednost", Namespace="http://schemas.datacontract.org/2004/07/SCADA")]
    [System.SerializableAttribute()]
    public partial class TagVrednost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tag_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double vrednostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime vreme_kreacijeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tag_name {
            get {
                return this.tag_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.tag_nameField, value) != true)) {
                    this.tag_nameField = value;
                    this.RaisePropertyChanged("tag_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double vrednost {
            get {
                return this.vrednostField;
            }
            set {
                if ((this.vrednostField.Equals(value) != true)) {
                    this.vrednostField = value;
                    this.RaisePropertyChanged("vrednost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime vreme_kreacije {
            get {
                return this.vreme_kreacijeField;
            }
            set {
                if ((this.vreme_kreacijeField.Equals(value) != true)) {
                    this.vreme_kreacijeField = value;
                    this.RaisePropertyChanged("vreme_kreacije");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlarmInformacija", Namespace="http://schemas.datacontract.org/2004/07/SCADA")]
    [System.SerializableAttribute()]
    public partial class AlarmInformacija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ime_velicineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prioritetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime vreme_aktivacijeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ime_velicine {
            get {
                return this.ime_velicineField;
            }
            set {
                if ((object.ReferenceEquals(this.ime_velicineField, value) != true)) {
                    this.ime_velicineField = value;
                    this.RaisePropertyChanged("ime_velicine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prioritet {
            get {
                return this.prioritetField;
            }
            set {
                if ((object.ReferenceEquals(this.prioritetField, value) != true)) {
                    this.prioritetField = value;
                    this.RaisePropertyChanged("prioritet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tip {
            get {
                return this.tipField;
            }
            set {
                if ((object.ReferenceEquals(this.tipField, value) != true)) {
                    this.tipField = value;
                    this.RaisePropertyChanged("tip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime vreme_aktivacije {
            get {
                return this.vreme_aktivacijeField;
            }
            set {
                if ((this.vreme_aktivacijeField.Equals(value) != true)) {
                    this.vreme_aktivacijeField = value;
                    this.RaisePropertyChanged("vreme_aktivacije");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IReport_Manager")]
    public interface IReport_Manager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/DoWork", ReplyAction="http://tempuri.org/IReport_Manager/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/DoWork", ReplyAction="http://tempuri.org/IReport_Manager/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/sveVrednostiSaOdredjenimIdentifikatorom", ReplyAction="http://tempuri.org/IReport_Manager/sveVrednostiSaOdredjenimIdentifikatoromRespons" +
            "e")]
        ReportManager.ServiceReference.TagVrednost[] sveVrednostiSaOdredjenimIdentifikatorom(string tag_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/sveVrednostiSaOdredjenimIdentifikatorom", ReplyAction="http://tempuri.org/IReport_Manager/sveVrednostiSaOdredjenimIdentifikatoromRespons" +
            "e")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference.TagVrednost[]> sveVrednostiSaOdredjenimIdentifikatoromAsync(string tag_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/poslednjaVrednostDItaga", ReplyAction="http://tempuri.org/IReport_Manager/poslednjaVrednostDItagaResponse")]
        ReportManager.ServiceReference.TagVrednost[] poslednjaVrednostDItaga();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/poslednjaVrednostDItaga", ReplyAction="http://tempuri.org/IReport_Manager/poslednjaVrednostDItagaResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference.TagVrednost[]> poslednjaVrednostDItagaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/poslednjaVrednostAItaga", ReplyAction="http://tempuri.org/IReport_Manager/poslednjaVrednostAItagaResponse")]
        ReportManager.ServiceReference.TagVrednost[] poslednjaVrednostAItaga();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/poslednjaVrednostAItaga", ReplyAction="http://tempuri.org/IReport_Manager/poslednjaVrednostAItagaResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference.TagVrednost[]> poslednjaVrednostAItagaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/sveVrednostiTagovaUOdredjenomVremenu", ReplyAction="http://tempuri.org/IReport_Manager/sveVrednostiTagovaUOdredjenomVremenuResponse")]
        ReportManager.ServiceReference.TagVrednost[] sveVrednostiTagovaUOdredjenomVremenu(System.DateTime pocetak, System.DateTime kraj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/sveVrednostiTagovaUOdredjenomVremenu", ReplyAction="http://tempuri.org/IReport_Manager/sveVrednostiTagovaUOdredjenomVremenuResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference.TagVrednost[]> sveVrednostiTagovaUOdredjenomVremenuAsync(System.DateTime pocetak, System.DateTime kraj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/sviAlarmiOdredjenVremPeriod", ReplyAction="http://tempuri.org/IReport_Manager/sviAlarmiOdredjenVremPeriodResponse")]
        ReportManager.ServiceReference.AlarmInformacija[] sviAlarmiOdredjenVremPeriod(System.DateTime pocetak, System.DateTime kraj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/sviAlarmiOdredjenVremPeriod", ReplyAction="http://tempuri.org/IReport_Manager/sviAlarmiOdredjenVremPeriodResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference.AlarmInformacija[]> sviAlarmiOdredjenVremPeriodAsync(System.DateTime pocetak, System.DateTime kraj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/sviAlarmiOdredjenogPrioriteta", ReplyAction="http://tempuri.org/IReport_Manager/sviAlarmiOdredjenogPrioritetaResponse")]
        ReportManager.ServiceReference.AlarmInformacija[] sviAlarmiOdredjenogPrioriteta(string prioritet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/sviAlarmiOdredjenogPrioriteta", ReplyAction="http://tempuri.org/IReport_Manager/sviAlarmiOdredjenogPrioritetaResponse")]
        System.Threading.Tasks.Task<ReportManager.ServiceReference.AlarmInformacija[]> sviAlarmiOdredjenogPrioritetaAsync(string prioritet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/Login", ReplyAction="http://tempuri.org/IReport_Manager/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport_Manager/Login", ReplyAction="http://tempuri.org/IReport_Manager/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReport_ManagerChannel : ReportManager.ServiceReference.IReport_Manager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Report_ManagerClient : System.ServiceModel.ClientBase<ReportManager.ServiceReference.IReport_Manager>, ReportManager.ServiceReference.IReport_Manager {
        
        public Report_ManagerClient() {
        }
        
        public Report_ManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Report_ManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Report_ManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Report_ManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public ReportManager.ServiceReference.TagVrednost[] sveVrednostiSaOdredjenimIdentifikatorom(string tag_name) {
            return base.Channel.sveVrednostiSaOdredjenimIdentifikatorom(tag_name);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference.TagVrednost[]> sveVrednostiSaOdredjenimIdentifikatoromAsync(string tag_name) {
            return base.Channel.sveVrednostiSaOdredjenimIdentifikatoromAsync(tag_name);
        }
        
        public ReportManager.ServiceReference.TagVrednost[] poslednjaVrednostDItaga() {
            return base.Channel.poslednjaVrednostDItaga();
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference.TagVrednost[]> poslednjaVrednostDItagaAsync() {
            return base.Channel.poslednjaVrednostDItagaAsync();
        }
        
        public ReportManager.ServiceReference.TagVrednost[] poslednjaVrednostAItaga() {
            return base.Channel.poslednjaVrednostAItaga();
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference.TagVrednost[]> poslednjaVrednostAItagaAsync() {
            return base.Channel.poslednjaVrednostAItagaAsync();
        }
        
        public ReportManager.ServiceReference.TagVrednost[] sveVrednostiTagovaUOdredjenomVremenu(System.DateTime pocetak, System.DateTime kraj) {
            return base.Channel.sveVrednostiTagovaUOdredjenomVremenu(pocetak, kraj);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference.TagVrednost[]> sveVrednostiTagovaUOdredjenomVremenuAsync(System.DateTime pocetak, System.DateTime kraj) {
            return base.Channel.sveVrednostiTagovaUOdredjenomVremenuAsync(pocetak, kraj);
        }
        
        public ReportManager.ServiceReference.AlarmInformacija[] sviAlarmiOdredjenVremPeriod(System.DateTime pocetak, System.DateTime kraj) {
            return base.Channel.sviAlarmiOdredjenVremPeriod(pocetak, kraj);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference.AlarmInformacija[]> sviAlarmiOdredjenVremPeriodAsync(System.DateTime pocetak, System.DateTime kraj) {
            return base.Channel.sviAlarmiOdredjenVremPeriodAsync(pocetak, kraj);
        }
        
        public ReportManager.ServiceReference.AlarmInformacija[] sviAlarmiOdredjenogPrioriteta(string prioritet) {
            return base.Channel.sviAlarmiOdredjenogPrioriteta(prioritet);
        }
        
        public System.Threading.Tasks.Task<ReportManager.ServiceReference.AlarmInformacija[]> sviAlarmiOdredjenogPrioritetaAsync(string prioritet) {
            return base.Channel.sviAlarmiOdredjenogPrioritetaAsync(prioritet);
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
    }
}
