//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trending.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDatabseManager")]
    public interface IDatabseManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabseManager/SendNotification", ReplyAction="http://tempuri.org/IDatabseManager/SendNotificationResponse")]
        void SendNotification(object tag, int brojTaga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatabseManager/SendNotification", ReplyAction="http://tempuri.org/IDatabseManager/SendNotificationResponse")]
        System.Threading.Tasks.Task SendNotificationAsync(object tag, int brojTaga);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatabseManagerChannel : Trending.ServiceReference.IDatabseManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabseManagerClient : System.ServiceModel.ClientBase<Trending.ServiceReference.IDatabseManager>, Trending.ServiceReference.IDatabseManager {
        
        public DatabseManagerClient() {
        }
        
        public DatabseManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabseManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabseManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabseManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendNotification(object tag, int brojTaga) {
            base.Channel.SendNotification(tag, brojTaga);
        }
        
        public System.Threading.Tasks.Task SendNotificationAsync(object tag, int brojTaga) {
            return base.Channel.SendNotificationAsync(tag, brojTaga);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITagProcessing", CallbackContract=typeof(Trending.ServiceReference.ITagProcessingCallback))]
    public interface ITagProcessing {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagProcessing/DoWork", ReplyAction="http://tempuri.org/ITagProcessing/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagProcessing/DoWork", ReplyAction="http://tempuri.org/ITagProcessing/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagProcessing/PrikazVrednostiUlaznihTagova", ReplyAction="http://tempuri.org/ITagProcessing/PrikazVrednostiUlaznihTagovaResponse")]
        string PrikazVrednostiUlaznihTagova();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagProcessing/PrikazVrednostiUlaznihTagova", ReplyAction="http://tempuri.org/ITagProcessing/PrikazVrednostiUlaznihTagovaResponse")]
        System.Threading.Tasks.Task<string> PrikazVrednostiUlaznihTagovaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagProcessing/TagProccesingInitalization", ReplyAction="http://tempuri.org/ITagProcessing/TagProccesingInitalizationResponse")]
        void TagProccesingInitalization();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagProcessing/TagProccesingInitalization", ReplyAction="http://tempuri.org/ITagProcessing/TagProccesingInitalizationResponse")]
        System.Threading.Tasks.Task TagProccesingInitalizationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITagProcessingCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITagProcessing/OnNotificationSent")]
        void OnNotificationSent(object tag, int brojTaga);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITagProcessingChannel : Trending.ServiceReference.ITagProcessing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TagProcessingClient : System.ServiceModel.DuplexClientBase<Trending.ServiceReference.ITagProcessing>, Trending.ServiceReference.ITagProcessing {
        
        public TagProcessingClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public TagProcessingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public TagProcessingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TagProcessingClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public TagProcessingClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string PrikazVrednostiUlaznihTagova() {
            return base.Channel.PrikazVrednostiUlaznihTagova();
        }
        
        public System.Threading.Tasks.Task<string> PrikazVrednostiUlaznihTagovaAsync() {
            return base.Channel.PrikazVrednostiUlaznihTagovaAsync();
        }
        
        public void TagProccesingInitalization() {
            base.Channel.TagProccesingInitalization();
        }
        
        public System.Threading.Tasks.Task TagProccesingInitalizationAsync() {
            return base.Channel.TagProccesingInitalizationAsync();
        }
    }
}
